server:
  port: 10000
  
spring:
  data:
    redis:
      host: my-redis-master.redis.svc.cluster.local
      port: 6379
user-service:
  base-url: http://user-service:10000
  

jwt:
  secret: "MySuperSecureSecretKey_ForStudyLinker_App_2025_AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJ"
  expiration: 3600000


logging:
  level:
    # [핵심] 스프링 웹 처리 과정을 전부 찍어봄
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    # 컨트롤러 매핑 과정을 상세히 확인 (어떤 URL이 어떤 메서드랑 연결되는지)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
