server:
  port: 10000

user-service:
#  base-url: http://user-service:10000
  base-url: http://localhost:10001

jwt:
  secret: "MySuperSecureSecretKey_ForStudyLinker_App_2025_AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJ"
  expiration: 3600000
