server:
  port: 10000

spring:
  datasource:
    url: jdbc:mariadb://mariadb-primary.c3kkm2iwaeig.ap-northeast-2.rds.amazonaws.com:3306/studydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: admin1234!
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: system-service-hikari

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "MySuperSecureSecretKey_ForStudyLinker_App_2025_AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJ"
  expiration: 3600000

aws:
  region: ap-northeast-2
  rds-instance-id: studydb-instance
  backup:
    enabled: false   # ğŸ”¥ ë¡œì»¬ì—ì„œë§Œ false ë¡œ ë‘ê³ , ë‚˜ì¤‘ì— ìš´ì˜ì€ true

management:
  endpoints:
    web:
      exposure:
        include: health,info
