server:
  port: 10000

jwt:
  secret: "MySuperSecureSecretKey_ForStudyLinker_App_2025_AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJ"
  expiration: 3600000   # 1 hour

spring:
  datasource:
    url: jdbc:mariadb://mariadb-primary.c3kkm2iwaeig.ap-northeast-2.rds.amazonaws.com:3306/studydb
    username: admin
    password: admin1234!
    driver-class-name: org.mariadb.jdbc.Driver

    # â­ HikariCP ì»¤ë„¥ì…˜ í’€ ì„¤ì • ì¶”ê°€
    hikari:
      maximum-pool-size: 10       # ğŸ”¥ ì»¤ë„¥ì…˜ í’€ ìµœëŒ€ 10ê°œ (MSAì—ì„œëŠ” ë°˜ë“œì‹œ ì¤„ì´ê¸°)
      minimum-idle: 5
      idle-timeout: 600000        # 10ë¶„
      max-lifetime: 1800000       # 30ë¶„ (DB wait_timeoutë³´ë‹¤ ì‘ê²Œ ìœ ì§€)
      connection-timeout: 30000   # ì»¤ë„¥ì…˜ ëª» ì–»ìœ¼ë©´ 30ì´ˆ í›„ timeout

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.study.study: DEBUG
